apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: runme2
    tier: challenge
  name: runme2
spec:
  replicas: 3
  selector:
    matchLabels:
      app: runme2
  template:
    metadata:
      annotations:
        apparmor.security.beta.kubernetes.io/defaultProfileName: runtime/default
        seccomp.security.alpha.kubernetes.io/pod: docker/default
      labels:
        app: runme2
        networkpolicy: allow_egress
        tier: challenge
    spec:
      automountServiceAccountToken: false
      containers:
      - env: []
        image: gcr.io/bsides-sf-ctf-2021/runme2
        name: runme2
        ports:
        - containerPort: 1337
          protocol: TCP
        resources:
          limits:
            cpu: '1'
            memory: 1Gi
          requests:
            cpu: 100m
            memory: 32Mi
        securityContext:
          allowPrivilegeEscalation: false
      volumes: []
