apiVersion: v1
kind: Service
metadata:
  labels:
    app: runme2
  name: runme2
spec:
  loadBalancerIP: 35.247.41.3
  ports:
  - port: 1337
    protocol: TCP
    targetPort: 1337
  selector:
    app: runme2
  type: LoadBalancer
