apiVersion: v1
kind: Service
metadata:
  labels:
    app: runme3
  name: runme3
spec:
  loadBalancerIP: 35.227.145.44
  ports:
  - port: 1337
    protocol: TCP
    targetPort: 1337
  selector:
    app: runme3
  type: LoadBalancer
