apiVersion: v1
kind: Service
metadata:
  labels:
    app: runme
  name: runme
spec:
  loadBalancerIP: 35.197.71.193
  ports:
  - port: 1337
    protocol: TCP
    targetPort: 1337
  selector:
    app: runme
  type: LoadBalancer
